### ISSUE TITLE
APN requests possibly delay socket event emit

### ISSUE THREAD

**Issue by heisler98** [tiberloop/flaskchat#42]
I've noticed via logging that APN requests are sent out in the midst of parsing open sockets. I noticed the latency for receiving a message from the server was far less in a channel with 1 member (me, who had an open socket) than a channel with multiple members who were disconnected. I am curious whether the APN requests "mid-activity" cause a delay in the server emitting a sent message to open sockets.

**Comment by colingoodman** [comment]
This is a good catch and I can definitely reorganize the code to obtain some speed-up.

**Comment by heisler98** [comment]
In addition to APN requests _delaying_ socket emission, if the APN request fails (see below logs), the socket emission never occurs. I imagine this would be resolved upon your planned refactoring, but just an FYI. 

```Jul 13 23:24:21 macpro python3.9[1376966]: [2021-07-13 23:24:21,801] INFO in sockets: {'include_image': False, 'text': 'Scrolling? 😁', 'username': 'hunter', 'room': '60ec6c89751e3f5bd5bec4d2'}
Jul 13 23:24:21 macpro python3.9[1376966]: 127.0.0.1 - - [13/Jul/2021 23:24:21] "POST /socket.io/?transport=polling&b64=1&EIO=4&sid=TzMRdIfFdQRcvp50AAHe HTTP/1.1" 200 -
Jul 13 23:24:21 macpro python3.9[1376966]: [2021-07-13 23:24:21,806] INFO in sockets: 60eca292593abde8a78b569e (hunter) has sent message to the room 60ec6c89751e3f5bd5bec4d2 at 2021-07-13 23:24:21.802600
Jul 13 23:24:21 macpro python3.9[1376966]: [2021-07-13 23:24:21,807] INFO in sockets: No open socket for 60ec6b28751e3f5bd5bec4cd, trying APN
Jul 13 23:24:21 macpro python3.9[1376966]: [2021-07-13 23:24:21,807] INFO in sockets: ['1459d654b48cd99fc8d874ba468a50c52868be8d82299e958863d1e63cf95937', '3a423d51854cf2628f139e54798b2518dd2d1c63e7dc6fd548c5ba5ce88967c4', '71bcac07f4d1f2c2b3ae1b784093f219af428fb59283d70664e5ba43711a0282']
Jul 13 23:24:21 macpro python3.9[1376966]: [2021-07-13 23:24:21,807] INFO in sockets: NOTIF: 1459d654b48cd99fc8d874ba468a50c52868be8d82299e958863d1e63cf95937, 60ec6b28751e3f5bd5bec4cd
Jul 13 23:24:21 macpro python3.9[1376966]: Exception in thread Thread-23774:
Jul 13 23:24:21 macpro python3.9[1376966]: Traceback (most recent call last):
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jul 13 23:24:21 macpro python3.9[1376966]:     self.run()
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Jul 13 23:24:21 macpro python3.9[1376966]:     self._target(*self._args, **self._kwargs)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/socketio/server.py", line 690, in _handle_event_internal
Jul 13 23:24:21 macpro python3.9[1376966]:     r = server._trigger_event(data[0], namespace, sid, *data[1:])
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/socketio/server.py", line 714, in _trigger_event
Jul 13 23:24:21 macpro python3.9[1376966]:     return self.handlers[namespace][event](*args)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 284, in _handler
Jul 13 23:24:21 macpro python3.9[1376966]:     return self._handle_event(handler, message, namespace, sid,
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_socketio/__init__.py", line 767, in _handle_event
Jul 13 23:24:21 macpro python3.9[1376966]:     ret = handler(*args)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 125, in decorator
Jul 13 23:24:21 macpro python3.9[1376966]:     return current_app.ensure_sync(fn)(*args, **kwargs)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flaskchat/api/sockets.py", line 144, in handle_send_message_event
Jul 13 23:24:21 macpro python3.9[1376966]:     resp = notification_interface.send_payload(new_payload, token)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flaskchat/library/apns.py", line 53, in send_payload
Jul 13 23:24:21 macpro python3.9[1376966]:     resp = self.conn.get_response()
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 312, in get_response
Jul 13 23:24:21 macpro python3.9[1376966]:     return HTTP20Response(stream.getheaders(), stream)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/stream.py", line 230, in getheaders
Jul 13 23:24:21 macpro python3.9[1376966]:     self._recv_cb(stream_id=self.stream_id)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 768, in _recv_cb
Jul 13 23:24:21 macpro python3.9[1376966]:     self._get_stream(stream_id)
Jul 13 23:24:21 macpro python3.9[1376966]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 289, in _get_stream
Jul 13 23:24:21 macpro python3.9[1376966]:     raise StreamResetError("Stream forcefully closed")
Jul 13 23:24:21 macpro python3.9[1376966]: hyper.http20.exceptions.StreamResetError: Stream forcefully closed
Jul 13 23:24:23 macpro python3.9[1376966]: 127.0.0.1 - - [13/Jul/2021 23:24:23] "GET /socket.io/?transport=polling&b64=1&EIO=4&sid=TzMRdIfFdQRcvp50AAHe HTTP/1.1" 200 -
Jul 13 23:24:23 macpro python3.9[1376966]: 127.0.0.1 - - [13/Jul/2021 23:24:23] "POST /socket.io/?transport=polling&b64=1&EIO=4&sid=TzMRdIfFdQRcvp50AAHe HTTP/1.1" 200 -```

**Comment by heisler98** [comment]
This is still an issue as of 7/18/2021 at 8:40pm. 
```Jul 18 20:39:00 macpro python3.9[654567]: b'{"reason":"ExpiredProviderToken"}'
Jul 18 20:39:00 macpro python3.9[654567]: 403
Jul 18 20:39:00 macpro python3.9[654567]: b'{"reason":"ExpiredProviderToken"}'
Jul 18 20:39:00 macpro python3.9[654567]: 403
Jul 18 20:39:00 macpro python3.9[654567]: b'{"reason":"ExpiredProviderToken"}'
Jul 18 20:39:00 macpro python3.9[654567]: 403
Jul 18 20:39:00 macpro python3.9[654567]: [2021-07-18 20:39:00,782] INFO in sockets: 403 : b'' as response from APNS for 9a3ed50d066867187711721cbf6dd58cddc2f6c90e4177c54d5ed490734ed282.
Jul 18 20:39:00 macpro python3.9[654567]: [2021-07-18 20:39:00,971] INFO in sockets: 403 : b'' as response from APNS for 21aaf8cf07d82bd2c4d9b71d4a2fea522473cdafb24fdd64fb382e78fc094ef9.
Jul 18 20:39:01 macpro python3.9[654567]: [2021-07-18 20:39:01,160] INFO in sockets: 403 : b'' as response from APNS for e781855f9b3a151c55b1882672d784e36636fecacefd24a31ab2a989ae5eea6b.
Jul 18 20:39:01 macpro python3.9[654567]: [2021-07-18 20:39:01,348] INFO in sockets: 403 : b'' as response from APNS for 674cbb320d3c223f91a770ef58f7141239595bbcac249bed651717517eece09c.
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,110] INFO in sockets: 60eca292593abde8a78b569e (hunter) has sent message to the room 60ec6c89751e3f5bd5bec4d2 at 1626658753.1085389
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,112] INFO in sockets: Sent to fFVFzOC5puSzjzV_AACl
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,114] INFO in sockets: Sent to zuw7LyXtd2O-wrsMAACj
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,302] INFO in sockets: 403 : b'' as response from APNS for 1459d654b48cd99fc8d874ba468a50c52868be8d82299e958863d1e63cf95937.
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,491] INFO in sockets: 403 : b'' as response from APNS for 3a423d51854cf2628f139e54798b2518dd2d1c63e7dc6fd548c5ba5ce88967c4.
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,679] INFO in sockets: 403 : b'' as response from APNS for 71bcac07f4d1f2c2b3ae1b784093f219af428fb59283d70664e5ba43711a0282.
Jul 18 20:39:13 macpro python3.9[654567]: [2021-07-18 20:39:13,868] INFO in sockets: 403 : b'' as response from APNS for e96887d49599723459a5525fce0ce1b8c68d50311d6651ed95827b2a310ddd17.
Jul 18 20:39:14 macpro python3.9[654567]: [2021-07-18 20:39:14,056] INFO in sockets: 403 : b'' as response from APNS for 447ae8b25220e565b493881ec1be95fd813b1287a4cce0c4587dfcf263eb948f.
Jul 18 20:39:14 macpro python3.9[654567]: [2021-07-18 20:39:14,244] INFO in sockets: 403 : b'' as response from APNS for 9a3ed50d066867187711721cbf6dd58cddc2f6c90e4177c54d5ed490734ed282.
Jul 18 20:39:14 macpro python3.9[654567]: [2021-07-18 20:39:14,432] INFO in sockets: 403 : b'' as response from APNS for 21aaf8cf07d82bd2c4d9b71d4a2fea522473cdafb24fdd64fb382e78fc094ef9.
Jul 18 20:39:14 macpro python3.9[654567]: [2021-07-18 20:39:14,620] INFO in sockets: 403 : b'' as response from APNS for e781855f9b3a151c55b1882672d784e36636fecacefd24a31ab2a989ae5eea6b.
Jul 18 20:39:14 macpro python3.9[654567]: [2021-07-18 20:39:14,810] INFO in sockets: 403 : b'' as response from APNS for 674cbb320d3c223f91a770ef58f7141239595bbcac249bed651717517eece09c.```

**Comment by colingoodman** [comment]
#84
