### ISSUE TITLE
APNs connection stream "forcefully closed"

### ISSUE THREAD

**Issue by heisler98** [tiberloop/flaskchat#84]
This exception occurred when sending a message after several hours of inactivity:
```
Jul 25 20:07:08 macpro python3.9[822230]: Traceback (most recent call last):
Jul 25 20:07:08 macpro python3.9[822230]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jul 25 20:07:08 macpro python3.9[822230]:     self.run()
Jul 25 20:07:08 macpro python3.9[822230]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Jul 25 20:07:08 macpro python3.9[822230]:     self._target(*self._args, **self._kwargs)
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flaskchat/api/sockets.py", line 184, in handle_apns_load
Jul 25 20:07:08 macpro python3.9[822230]:     success = notification_interface.send_payload(new_payload, token)
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flaskchat/library/apns.py", line 84, in send_payload
Jul 25 20:07:08 macpro python3.9[822230]:     resp = self.conn.get_response()
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 312, in get_response
Jul 25 20:07:08 macpro python3.9[822230]:     return HTTP20Response(stream.getheaders(), stream)
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/stream.py", line 230, in getheaders
Jul 25 20:07:08 macpro python3.9[822230]:     self._recv_cb(stream_id=self.stream_id)
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 768, in _recv_cb
Jul 25 20:07:08 macpro python3.9[822230]:     self._get_stream(stream_id)
Jul 25 20:07:08 macpro python3.9[822230]:   File "/tiny/flask_venv/lib/python3.9/site-packages/hyper/http20/connection.py", line 289, in _get_stream
Jul 25 20:07:08 macpro python3.9[822230]:     raise StreamResetError("Stream forcefully closed")
Jul 25 20:07:08 macpro python3.9[822230]: hyper.http20.exceptions.StreamResetError: Stream forcefully closed
```

I know that APNs requests that connections get reused and can stay open by sending a PING frame every so often.

**Comment by heisler98** [comment]
Also, it appears provider tokens are expiring.
```
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
Jul 25 20:25:26 macpro python3.9[821298]: Generated APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
Jul 25 20:25:26 macpro python3.9[821298]: Generated APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
Jul 25 20:25:26 macpro python3.9[821298]: Generated APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
Jul 25 20:25:26 macpro python3.9[821298]: Generated APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
Jul 25 20:25:26 macpro python3.9[821298]: Generated APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: Sent APNS payload.
Jul 25 20:25:26 macpro python3.9[821298]: b'{"reason":"ExpiredProviderToken"}'
```

**Comment by heisler98** [comment]
Furthermore, I sent a message and saw the following in the logs (note the timestamp):
```
Jul 25 21:15:44 macpro python3.9[992929]: Generated APNS payload.
Jul 25 21:15:44 macpro python3.9[992929]: DB: SAVE_MESSAGE 60f0d455f24ff568aab88641 Hey 9:15 60ec85f1593abde8a78b5644 1627265744.6831048
Jul 25 21:15:44 macpro python3.9[992929]: Get latest bucket number 60f0d455f24ff568aab88641 1
```
It's currently 9:18pm. No `Sent APNS payload.` to be found.

**Comment by heisler98** [comment]
So far, I've noticed this happens every night. I restart flask every night to abate this issue.

**Comment by colingoodman** [comment]
Pushed a fix to dev where a new thread is created on instantiation of my apns object that ensures a new token is created at least every 45 minutes. Apple requires no less often than 60.
