### ISSUE TITLE
Implement deletion via API

### ISSUE THREAD

**Issue by heisler98** [tiberloop/flaskchat#91]
Gods should be able to purge users & rooms from the database via the API. The API ought to account for the following scenarios (given that we've run into them several times over the past couple weeks):

- Deleting a user removes it from every room to which it belonged, and deletes every DM any other user had with it. 
- Deleting a room deletes the room_members entries for that particular room. 

Currently, the backend is failing with 500 errors because users were deleted without deleting their accompanying room_member entries.

```Aug 03 22:59:05 macpro python3.9[4076741]: Traceback (most recent call last):
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
Aug 03 22:59:05 macpro python3.9[4076741]:     response = self.full_dispatch_request()
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
Aug 03 22:59:05 macpro python3.9[4076741]:     rv = self.handle_user_exception(e)
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
Aug 03 22:59:05 macpro python3.9[4076741]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
Aug 03 22:59:05 macpro python3.9[4076741]:     rv = self.dispatch_request()
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
Aug 03 22:59:05 macpro python3.9[4076741]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 125, in decorator
Aug 03 22:59:05 macpro python3.9[4076741]:     return current_app.ensure_sync(fn)(*args, **kwargs)
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flaskchat/api/rooms.py", line 154, in single_room
Aug 03 22:59:05 macpro python3.9[4076741]:     return jsonify(return_room(room, user.username, user_id)), 200
Aug 03 22:59:05 macpro python3.9[4076741]:   File "/tiny/flaskchat/api/rooms.py", line 398, in return_room
Aug 03 22:59:05 macpro python3.9[4076741]:     new_name = other_user.real_name
Aug 03 22:59:05 macpro python3.9[4076741]: AttributeError: 'NoneType' object has no attribute 'real_name'
```

Furthermore, some code to check internal DB consistency may be helpful. (e.g. are there "ghost" room members for which there are no actual user documents?)

**Comment by heisler98** [comment]
I initially figured that the "return_room" function ought to check for non-existent members. That would be failing safely. I prefer to fail loudly so we can fix the underlying issue. That design decision is yours.
